---
################################################################################
# createrepo wrapper
- name: Perform local createrepo with our finished rpms
  block:
    - name: "Run createrepo for {{ repo_drop_path }}"
      command:
        argv:
          - '/usr/bin/createrepo_c'
          - '--xz'
          - '--checksum=sha256'
          - '--revision={{ full }}'
          - '--workers=8'
          - '--distro=cpe:/o:{{ distro }}:{{ distro }}:{{ major }},{{ mock_vendor }} {{ major }}'
          - '{{ repo_drop_path }}'
      register: createrepo_finish
      ignore_errors: true
      tags:
        - createrepo

    - name: "Run modifyrepo for module at {{ repo_drop_path }}"
      command:
        argv:
          - '/usr/bin/modifyrepo_c'
          - '--mdtype=modules'
          - '{{ repo_drop_path_results }}/module.{{ mock_arch }}.yaml'
          - '{{ repo_drop_path }}/repodata'
          - '--compress'
          - '--compress-type=xz'
      register: modifyrepo_finish
      ignore_errors: true
      when: module_mode|bool
      tags:
        - createrepo
  rescue:
    - name: We failed, display the error.
      debug:
        msg: "Failed to setup repo: {{ ansible_failed_result }}"

    - name: Perform full cleanup
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ mock_builder_rpmbuild_dir }}'
        - '{{ mock_builder_source_dir }}'
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
        - '{{ mock_builder_module_dir }}'
        - '/var/tmp/.build_in_progress'

    - name: Fail when there's an error in the block
      fail:
        msg: "Exiting entire play"
  when:
    - (repo_host == "localhost") or (transfer_type == "nfs") or (module_mode|bool)
  tags:
    - createrepo

- name: Perform remote createrepo
  block:
    - name: createrepo
      debug:
        msg: createrepo
  when:
    - (not repo_host == "localhost") and (not transfer_type == "nfs")
  tags:
    - createrepo
...
