---
# set up the mock environment
- name: "Ensure mock and git is installed"
  package:
    state: present
    name:
      - mock
      - rpm-build
      - createrepo_c
      - git
      - rsync
  become: true
  become_user: root
  tags:
    - mock
    - mock_setup

################################################################################
# The user that builds the RPMs that should be part of the mock group
- name: "Ensure the {{ mock_builder }} user exists and is part of the mock group"
  user:
    name: "{{ mock_builder }}"
    state: present
    uid: '11011'
    system: true
    groups:
      - mock
  become: true
  become_user: root
  tags:
    - mock
    - mock_setup

################################################################################
# Set up the rpmbuild environment, specifically for unpacking source RPM's or
# copying git source data and building the SRPM in the first place
- name: "Setup the {{ mock_builder }} rpmbuild and git environment"
  file:
    path: '{{ item }}'
    owner: '{{ mock_builder }}'
    group: '{{ mock_builder }}'
    mode: '0755'
    state: directory
  loop:
    - "{{ mock_builder_rpmbuild_dir }}"
    - "{{ mock_builder_rpmbuild_dir }}/SRPMS"
    - "{{ mock_builder_rpmbuild_dir }}/SOURCES"
    - "{{ mock_builder_rpmbuild_dir }}/SPECS"
    - "{{ mock_builder_source_dir }}"
  tags:
    - mock

- name: "Bootstrap, module, or solo builds"
  block:
    ###########################################################################
    # Set up the local repo - the mock builder user should have ownership
    - name: "Ensure the bootstrap repos for {{ mock_builder }} exit"
      file:
        path: '{{ item }}'
        owner: '{{ mock_builder }}'
        group: '{{ mock_builder }}'
        mode: '0755'
        state: directory
      loop:
        - "{{ repo_drop_path }}"
        - "{{ repo_drop_path_results }}"
      become: true
      become_user: root
      tags:
        - mock
        - module
        - solo
        - sig

    ##########################################################################
    # Create the repos if it isn't ready
    - name: "Stat the repo drop path repodata"
      stat:
        path: "{{ repo_drop_path }}/repodata"
      register: repodata_dir
      tags:
        - mock
        - module
        - solo
        - sig

    - name: "Run a createrepo if necessary"
      command:
        argv:
          - '/usr/bin/createrepo_c'
          - '--xz'
          - '--checksum=sha256'
          - '--revision={{ full }}'
          - '--workers=8'
          - '--distro=cpe:/o:{{ distro }}:{{ distro }}:{{ major }},{{ mock_vendor }} {{ major }}'
          - '{{ repo_drop_path }}'
      when:
        - not repodata_dir.stat.exists
      tags:
        - mock
        - module
        - solo
        - sig
  when:
    - (bootstrap|bool) or (sig_or_constraint|bool) or (module_mode|bool)
...
