---
# cleanup mock remains
- name: Remove deployed scripts and configs
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg"
    - "/home/{{ mock_builder }}/mock-wrapper.sh"
    - "{{ mock_builder_source_dir }}"
    - "{{ mock_builder_rpmbuild_dir }}"
    - "{{ mock_builder_module_dir }}"
    - "/var/lib/mock/{{ source_name }}"
  when:
    - enable_cleanup|bool
  tags:
    - mock
    - module
    - cleanup

- name: System is no longer in use
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "/var/tmp/.build_in_progress"
  tags:
    - mock
    - module
    - cleanup
...
