---
################################################################################
# module transfer wrapper
- name: Perform a local transfer
  block:
    - name: Identify all built RPMs and filter out as necessary
      find:
        paths: "/var/lib/mock/{{ source_name }}/results/{{ mock_build_root }}"
        recurse: true
        patterns:
          - '*.noarch.rpm'
          - '*.{{ mock_arch }}.rpm'
        excludes: "{{ module_filtered_rpms | default(omit) }}"
      register: result_build_rpms
      tags:
        - transfer
        - module

    - name: Identify the source RPMs
      find:
        paths: "/var/lib/mock/{{ source_name }}/results/{{ mock_build_root }}"
        recurse: true
        patterns: '*.src.rpm'
      register: result_src_rpms
      tags:
        - transfer
        - module

    - name: Identify all build logs
      find:
        paths: "/var/lib/mock/{{ source_name }}/results/{{ mock_build_root }}"
        recurse: true
        patterns: '*.log'
      register: result_build_logs
      tags:
        - transfer
        - module

    - name: Ensure all directories are setup for drop
      file:
        path: '{{ item }}'
        owner: '{{ mock_builder }}'
        group: '{{ mock_builder }}'
        mode: '0755'
        state: directory
      loop:
        - "{{ repo_drop_path }}"
        - "{{ repo_drop_path_results }}"
      become: true
      become_user: root
      tags:
        - transfer
        - module

    - name: Copy compiled RPMs into their proper spot
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path }}/"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_build_rpms.files }}"
      tags:
        - transfer
        - module

    - name: Copy source RPMs into the results area
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path_results }}/"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_src_rpms.files }}"
      tags:
        - transfer
        - module

    - name: Copy build logs into the results area
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path_results }}/{{ item.path.split('/')[-2] }}_{{ item.path.split('/')[-1] }}"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_build_logs.files }}"
      tags:
        - transfer
        - module

    - name: Copy mock configs
      copy:
        src: "{{ item }}"
        dest: "{{ repo_drop_path_results }}/"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      loop:
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
      tags:
        - transfer
        - module

  rescue:
    - name: We failed, display the error.
      debug:
        msg: "Failed to copy or setup dropbox: {{ ansible_failed_result }}"

    - name: Perform full cleanup
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ mock_builder_rpmbuild_dir }}'
        - '{{ mock_builder_source_dir }}'
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
        - '{{ mock_builder_module_dir }}'
        - '{{ repo_drop_path_results }}'
        - '/var/tmp/.build_in_progress'

    - name: Fail when there's an error in the block
      fail:
        msg: "Exiting entire play"
  when:
    - module_mode|bool
  tags:
    - transfer
...
